boomerang-io/flow.client.web

package-lock.json, package.json, src/Components/SwitchLinkExecutionConditionButton/SwitchLinkExecutionConditionButton.js, src/Components/TaskLinkExecutionConditionSwitcher/TaskLinkExecutionConditionSwitcher.js, src/Components/TextEditorModal/TextEditorModal.js, src/Components/WorkflowCloseButton/WorkflowCloseButton.js, src/Components/WorkflowEditButton/WorkflowEditButton.js, src/Components/WorkflowWarningButton/WorkflowWarningButton.tsx, src/Features/Activity/ActivityTable/ActivityTable.tsx, src/Features/Editor/__snapshots__/Editor.spec.js.snap, src/Features/Insights/CustomLegend/CustomLegend.js, src/Features/TaskTemplates/TaskTemplateOverview/TemplateConfigModal/TemplateConfigModalContent/TemplateConfigModalContent.tsx, src/Features/Teams/Teams.tsx
Jira Issue: 
https://github.com/boomerang-io/roadmap/issues/10
Build Number: 
N/A
To confirm that the issue is indeed fixed - try setting a workflow quota to 1 and then run two workflows in succession. The second workflow should display an error message in the modal that communicates to the user that there are too many workflows currently being run. This replaces the error of this situation causing a webapp crash.
=> fix: updated utils package and imports

src/ApiServer/fixtures/summaries.js, src/Components/CreateWorkflow/__snapshots__/CreateWorkflow.spec.js.snap, src/Features/Editor/Configure/Token/Token.tsx, src/Features/Editor/__snapshots__/Editor.spec.js.snap, src/Features/Execution/Main/ExecutionHeader/ExecutionHeader.js, src/Features/Execution/Main/ExecutionHeader/__snapshots__/ExecutionHeader.spec.js.snap, src/Features/Execution/Main/ExecutionHeader/executionHeader.module.scss, src/Features/Execution/__snapshots__/Execution.spec.js.snap
Related Issues(s): https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/38
Build Number: 3.0.86
Check "Execution/Main/ExecutionHeader"
=> [38] Ability to see a detailed kubernetes information

src/Components/CustomTaskNodeExecution/CustomTaskNodeExecution.tsx, src/Components/ManualApprovalNodeExecution/ManualApprovalNodeExecution.tsx, src/Components/ManualTaskNodeExecution/ManualTaskNodeExecution.tsx, src/Components/SetPropertyNodeExecution/SetPropertyNodeExecution.tsx, src/Components/SwitchNodeExecution/SwitchNodeExecution.js, src/Components/TemplateTaskNodeExecution/TemplateTaskNodeExecution.js, src/Components/WaitNodeExecution/WaitNodeExecution.tsx, src/Components/WorkflowNode/WorkflowNode.tsx, src/Features/Execution/Main/ExecutionTaskLog/TaskItem/TaskItem.js, src/Features/Execution/Main/ExecutionTaskLog/TaskItem/__snapshots__/TaskItem.spec.js.snap, src/Features/Execution/Main/ExecutionTaskLog/TaskItem/taskItem.module.scss, src/Features/Execution/Main/ExecutionTaskLog/__snapshots__/ExecutionTaskLog.spec.js.snap, src/Features/Execution/Main/ExecutionTaskLog/executionTaskLog.module.scss, src/Features/Execution/__snapshots__/Execution.spec.js.snap
Related Issues(s): https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/73
Build Number: 3.0.80
Check "Components/TemplateTaskNodeExecution" and "Execution/Main/ExecutionTaskLog/TaskItem".
Check on dev if clicking a node in the Execution diagram scrolls and focus the task log on the side.
=> [73] View and focus tasks log on click

src/ApiServer/fixtures/tasktemplate.js, src/Components/CreateWorkflow/__snapshots__/CreateWorkflow.spec.js.snap, src/Components/WorkflowCard/UpdateWorkflow/__snapshots__/UpdateWorkflow.spec.js.snap, src/Features/TaskTemplates/TaskTemplateOverview/EditTaskTemplateModal/EditTaskTemplateForm/EditTaskTemplateForm.tsx, src/Features/TaskTemplates/TaskTemplateOverview/EditTaskTemplateModal/EditTaskTemplateModal.tsx, src/Features/TaskTemplates/TaskTemplateOverview/TaskTemplateOverview.tsx, src/Types/index.tsx
=> feat: enable lifecycle task template

src/ApiServer/fixtures/featureFlags.js, src/ApiServer/fixtures/flowNavigation.js, src/Components/NoTeamsRedirectPrompt/NoTeamsRedirectPrompt.tsx, src/Components/NoTeamsRedirectPrompt/index.ts, src/Features/Insights/Insights.js, src/Features/Insights/workflowInsights.module.scss, src/Features/ManageTeamTasksContainer/ManageTeamTasksContainer.tsx, src/Features/TeamProperties/TeamPropertiesTable/TeamPropertiesTable.tsx, src/Features/Workflows/NoAccessRedirectPrompt/index.jsx, src/Features/Workflows/Workflows.tsx
Related Issues(s): https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/120
Build Number: 3.0.105
Updated "no teams view" on these features:
- Workflows
- Insights
- Manage -> team parameters
- Manage -> team tasks
=> [120] Team Tasks breaks with no Teams

package-lock.json, package.json, src/ApiServer/fixtures/summaries.js
https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/86
Build Number: 
3.0.96
=> Fix 86 standalone profile daks

server/package-lock.json, server/package.json
Related Issues(s): ISEEC-1611
Build Number: 3.0.102
=> [ISEEC-1611] Update Server dependencies

package-lock.json, package.json, src/ApiServer/fixtures/summaries.js, src/Components/CreateWorkflow/__snapshots__/CreateWorkflow.spec.js.snap, src/Components/WorkflowCard/UpdateWorkflow/__snapshots__/UpdateWorkflow.spec.js.snap, src/Features/Activity/Activity.tsx
https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/87
Build Number: 
3.0.99
=> fix: activity date picker

src/Features/ManageTeamTasks/TaskTemplateOverview/TemplateConfigModal/TemplateConfigModalContent/TemplateConfigModalContent.tsx, src/Features/TaskTemplates/TaskTemplateOverview/TemplateConfigModal/TemplateConfigModalContent/TemplateConfigModalContent.tsx
https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/129
Build Number: 
3.0.114
=> fix: task template fields default value

src/Features/ManageTeamTasks/TaskTemplateOverview/TemplateConfigModal/TemplateConfigModalContent/TemplateConfigModalContent.tsx, src/Features/TaskTemplates/TaskTemplateOverview/TemplateConfigModal/TemplateConfigModalContent/TemplateConfigModalContent.tsx
https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/129
Build Number: 
3.0.114
=> Fix 129 task default parameters

src/ApiServer/fixtures/workflowExecution.js, src/Components/ErrorModal/ErrorModal.tsx, src/Components/ErrorModal/errorModal.module.scss, src/Components/ErrorModal/index.tsx, src/Components/ErrorModal/markdown.css, src/Features/Execution/Main/ExecutionHeader/ExecutionHeader.js, src/Features/Execution/Main/ExecutionHeader/executionHeader.module.scss, src/Features/Execution/Main/ExecutionTaskLog/TaskItem/TaskItem.js
https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/141
Build Number: 
3.0.120
=> Feat 141 display workflow level error message

src/Components/WelcomeBanner/WelcomeBanner.js
https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/116
Build Number:
=> fix: update skacl us feedback link

src/Features/Editor/Configure/BuildWebhookModalContent/BuildWebhookModalContent.tsx
https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/152
Build Number: 
~3.0.132~ 3.0.133
=> fix: update webhook modal url

src/ApiServer/index.js, src/Config/appConfig.js, src/Features/Editor/Configure/Configure.tsx, src/Features/Editor/Configure/configure.module.scss, src/Features/Editor/Designer/Designer.tsx, src/Features/Editor/__snapshots__/Editor.spec.js.snap, src/Features/Execution/Main/ExecutionHeader/__snapshots__/ExecutionHeader.spec.js.snap, src/Features/Execution/__snapshots__/Execution.spec.js.snap, src/Features/Insights/CustomTooltip/__snapshots__/CustomTooltip.spec.js.snap, src/setupTests.js
https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/148
Build Number: 
~3.0.124~ 3.0.129
=> feat: update workflow custom labels text

src/Features/ManageTeamTasks/Sidenav/AddTaskTemplate/AddTaskTemplate.tsx, src/Features/ManageTeamTasks/Sidenav/AddTaskTemplate/AddTaskTemplateForm/AddTaskTemplateForm.tsx, src/Features/TaskTemplates/Sidenav/AddTaskTemplate/AddTaskTemplate.tsx, src/Features/TaskTemplates/Sidenav/AddTaskTemplate/AddTaskTemplateForm/AddTaskTemplateForm.tsx
https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/142
Build Number: 
3.0.131
=> fix: update text for create task

src/Components/CreateWorkflow/CreateWorkflowContainer/CreateWorkflowContainer.tsx, src/Components/CreateWorkflow/CreateWorkflowContent/CreateWorkflowContent.tsx, src/Components/CreateWorkflow/CreateWorkflowContent/__snapshots__/CreateWorkflowContent.spec.js.snap
https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/151
Build Number: 3.0.134
Updated CreateWorkflowContent to use selected team workflows as comparison.
=> fix [151] Creating new Workflow states Workflow Exists

src/Components/TaskUpdateModal/TaskUpdateModal.js, src/Features/Execution/Main/ExecutionTaskLog/TaskItem/TaskItem.js, src/Features/Execution/__snapshots__/Execution.spec.js.snap
Build Number: 
3.0.141
- Workflow Update Modals were not loading the defaultValues correctly
- Execution View Error Button bug
=> Fix workflow update default value and view error

package-lock.json, package.json, src/Features/App/Navbar/Navbar.tsx
Related Issues(s): https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/209
Build Number: 
Component library PR: https://github.com/boomerang-io/carbon-addons-boomerang-react/pull/31
=> Feat [209] Flow Docs Link

src/Features/Settings/Settings.tsx, src/Features/Settings/SettingsSection/SettingsSection.tsx, src/Features/Settings/SettingsSection/settingsSection.module.scss
Related Issues(s): https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/208
Build Number: 3.1.18
=> feat [208] Settings section description does not show

package-lock.json, package.json, src/ApiServer/fixtures/summaries.js, src/Components/CreateWorkflow/CreateWorkflowContent/constants.tsx, src/Features/Editor/Configure/BuildWebhookModalContent/BuildWebhookModalContent.tsx, src/Features/Editor/Configure/Configure.tsx, src/Features/Editor/Configure/ConfigureStorage/ConfigureStorage.tsx, src/Features/Editor/Configure/ConfigureStorage/index.tsx, src/Features/Editor/Configure/configure.module.scss, src/Types/index.tsx
https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/40
Build Number:
=> Feat 40 advanced pvc config

src/ApiServer/index.js, src/Features/ManageTeamTasks/Sidenav/AddTaskTemplate/AddTaskTemplateForm/AddTaskTemplateForm.tsx, src/Features/ManageTeamTasks/Sidenav/AddTaskTemplate/AddTaskTemplateForm/addTaskTemplateForm.module.scss, src/Features/ManageTeamTasks/Sidenav/AddTaskTemplate/AddTaskTemplateForm/constants.tsx, src/Features/TaskTemplates/Sidenav/AddTaskTemplate/AddTaskTemplateForm/AddTaskTemplateForm.tsx, src/Features/TaskTemplates/Sidenav/AddTaskTemplate/AddTaskTemplateForm/addTaskTemplateForm.module.scss, src/Features/TaskTemplates/Sidenav/AddTaskTemplate/AddTaskTemplateForm/constants.tsx, src/State/reducers/workflowRevision.js
Related Issues(s): https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/226
Build Number: 3.3.14
If the file doesn't have a description, the app errors when trying to get the length of the undefined description in one of the inputs, so would be good to merge this with main as well.
Also updated the messages to use InlineNotification.
=> Fix [226] Yaml Import Error

src/ApiServer/fixtures/index.js, src/ApiServer/fixtures/platformConfig.js, src/ApiServer/index.js, src/Config/servicesConfig.js, src/Features/App/App.tsx, src/Features/App/Navbar/Navbar.tsx, src/Types/index.tsx
Related Issues(s): N/A (unless there is a general cleanup issue?)
Build Number: N/A low risk change
Added some types and renamed `platformConfigData` -> `platformConfigData` for clarity
Not much to say, I was exploring another issue and wanted to get re-acquainted with the codebase again.
=> feat: add some typing to the top level

package-lock.json, package.json, src/Components/TemplateConfigModal/TemplateConfigModalContent/TemplateConfigModalContent.tsx, src/Features/Editor/Properties/PropertiesModal/PropertiesModalContent/PropertiesModalContent.tsx, src/Utils/isUrl.js, src/Utils/urlPropertySyntaxHelper.js
https://github.com/boomerang-io/roadmap/issues/238
Build Number: 
3.4.25
- Updated Task Definition Fields form and Workflow Editor Parameters form.
=> Fix 238 url property syntax

src/Features/Execution/Main/ExecutionTaskLog/TaskItem/OutputPropertiesLog/OutputPropertiesLog.tsx
https://github.com/boomerang-io/roadmap/issues/288
Build Number: 
3.4.23
=> feat: update results format handler

src/ApiServer/fixtures/workflowExecution.js, src/Components/CreateWorkflow/__snapshots__/CreateWorkflow.spec.js.snap, src/Components/PreviewConfig/__snapshots__/PreviewConfig.spec.js.snap, src/Components/WorkflowCard/UpdateWorkflow/__snapshots__/UpdateWorkflow.spec.js.snap, src/Features/Execution/Main/ExecutionTaskLog/TaskItem/OutputPropertiesLog/OutputPropertiesLog.tsx, src/Features/Execution/Main/ExecutionTaskLog/TaskItem/OutputPropertiesLog/PropertiesTable/PropertiesTable.tsx
https://github.com/boomerang-io/roadmap/issues/243
Build Number: 
3.4.27
=> fix: add description column to output params table

src/ApiServer/index.js, src/Components/CreateWorkflow/__snapshots__/CreateWorkflow.spec.js.snap, src/Components/WorkflowTaskForm/WorkflowTaskForm.js
https://github.com/boomerang-io/roadmap/issues/292
Build Number: 
3.4.28
=> fix: payload for workflow revision and available params

src/ApiServer/fixtures/tasktemplate.js, src/Components/RunWorkflowNodeDesigner/ConfigureInputsForm/ConfigureInputsForm.js, src/Features/Editor/__snapshots__/Editor.spec.js.snap, src/Features/TaskTemplates/__snapshots__/TaskTemplates.spec.js.snap
https://github.com/boomerang-io/roadmap/issues/304
Build Number: 
3.5.8
- Edit a User workflow and try to configure a Run Workflow task. Workflow dropdown should display user workflows.
- Tested things in qa since dev is not working for me at the moment.
=> fix: add check for user scope

src/ApiServer/fixtures/manualTasks.js, src/ApiServer/index.js, src/Components/CreateTemplateWorkflow/CreateTemplateWorkflow.spec.js, src/Components/EmptyState/EmptyState.tsx, src/Features/Actions/ActionsTable/ActionsTable.tsx, src/Features/Actions/ActionsTable/ApproveRejectActions/ApproveRejectActions.module.scss, src/Features/Actions/ActionsTable/ManualTask/ManualTask.module.scss, src/Features/Actions/ActionsTable/ManualTask/ManualTask.tsx, src/Features/Actions/ActionsTable/ManualTask/index.tsx
- closes https://github.com/boomerang-io/roadmap/issues/317
Build Number: 3.5.18
Check if modal is opening for Manual Tasks actions when clicking a row and if the "View Activity" link in the Actions table is redirecting correctly.
=> feat [317] Manual Task Actions have no interaction / modal

src/Config/appConfig.js
Related Issues(s):  closes https://github.com/boomerang-io/roadmap/issues/316
Build Number: N/A
Small change to the URL, just confirm that it is correct. I do see that the redirect isn't correct but that is an issue w/ the Docs app, not Flow.
I also cleaned up some dead code in the file.
N/A
=> Bug 316 docs url

src/Components/WorkflowsHeader/WorkflowsHeader.tsx
Related Issues(s): [#129](https://github.com/boomerang-io/flow.client.web/issues/129)
Minor text change. No adjustments to logic.
=> Minor adjustment to header text

server/package-lock.json, server/package.json
Closes #127 
Related Issues(s):  
ISEEC-2907
Build Number:  3.5.28
Ensure that the script is added in the environment that is configured to use it and that is makes tracking requests
=> feat: add instana support

src/ApiServer/fixtures/index.js, src/ApiServer/fixtures/taskTemplateValidate.js, src/ApiServer/index.js, src/Features/ManageTeamTasks/Sidenav/AddTaskTemplate/AddTaskTemplateForm/AddTaskTemplateForm.tsx, src/Features/TaskTemplates/Sidenav/AddTaskTemplate/AddTaskTemplateForm/AddTaskTemplateForm.tsx
=> fix: import task yaml error

.github/workflows/ci.yml, src/ApiServer/fixtures/tasktemplate.js, src/Components/EditTaskTemplateModal/EditTaskTemplateForm/EditTaskTemplateForm.tsx, src/Components/EditTaskTemplateModal/EditTaskTemplateForm/__snapshots__/EditTaskTemplateForm.spec.js.snap, src/Components/EditTaskTemplateModal/EditTaskTemplateModal.tsx, src/Features/ManageTeamTasks/Sidenav/AddTaskTemplate/AddTaskTemplateForm/AddTaskTemplateForm.tsx, src/Features/ManageTeamTasks/TaskTemplateOverview/TaskTemplateOverview.tsx, src/Features/TaskTemplates/Sidenav/AddTaskTemplate/AddTaskTemplateForm/AddTaskTemplateForm.tsx, src/Features/TaskTemplates/TaskTemplateOverview/TaskTemplateOverview.tsx, src/Features/TaskTemplates/TaskTemplateOverview/__snapshots__/TaskTemplateOverview.spec.js.snap
=> Flow v3 add support for serviceaccountname securitycontext

src/Features/App/App.tsx, src/Features/ManageTeamTasks/Sidenav/Sidenav.tsx
=> Cicd flow optimize 3.11.7

src/Components/WorkflowCard/WorkflowCard.tsx, src/Features/App/App.tsx, src/Features/Execution/Main/ExecutionHeader/ExecutionHeader.tsx, src/Features/Execution/Main/ExecutionHeader/__snapshots__/ExecutionHeader.spec.js.snap, src/Features/Execution/__snapshots__/Execution.spec.js.snap, src/Features/TeamDetailed/Workflows/Workflows.tsx, src/Features/UserDetailed/Workflows/Workflows.tsx, src/Features/UserDetailed/__snapshots__/UserDetailed.spec.js.snap
=> Add switch disable activity

src/Components/CreateWorkflow/CreateWorkflow.tsx, src/Features/Editor/Editor.tsx, src/Features/ManageTeamTasks/ManageTeamTasks.tsx, src/Features/Workflows/Workflows.tsx
=> Workflow task editor
